name: habitat
description: A simple habit tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/playstore.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/playstore.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/android/